[package]
name = "webfun-preview"
version = "0.1.0"
authors = ["Christoph Leimbrock <christoph.leimbrock@gmx.de>"]

[lib]
crate-type = ["staticlib"]

[dependencies]
byteorder = "*"
image = "*"
elapsed = "*"
